/*
 * VieFiles.java
 *
 * Created on __DATE__, __TIME__
 */

package com.example.ui;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

import com.example.model.Note;

/**
 *
 * @author  __USER__
 */
public class VieFiles extends javax.swing.JFrame {
	List<Note> list;

	/** Creates new form VieFiles */
	public VieFiles(List<Note> list) {
		initComponents();
		this.list = list;
		setListData();
	}

	private void setListData() {
		DefaultListModel dl = new DefaultListModel();
		for (int i = 0; i < list.size(); i++) {
			dl.addElement(list.get(i));
		}
		jList1.setModel(dl);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { " " };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jList1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jList1MouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jList1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(69, 69, 69).addComponent(
						jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
						244, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(87, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(40, 40, 40).addComponent(
						jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
						190, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(70, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jList1MouseClicked(java.awt.event.MouseEvent evt) {
		//System.out.println(list.get(jList1.getSelectedIndex()).getLocation());
	JPopupMenu p=new JPopupMenu();
	JMenuItem m1=new JMenuItem("View");
	JMenuItem m2=new JMenuItem("Download");
	p.add(m1);
	p.add(m2);
	p.show(jList1, evt.getX(),evt.getY());
	m1.addActionListener(new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent e) {
		try{
			Desktop d=Desktop.getDesktop();
			d.open(new File(list.get(jList1.getSelectedIndex()).getLocation()));
		}catch (Exception e1) {
			System.out.println(e1);
		}
		}
	});
	}

	/**
	 * @param args the command line arguments
	 */
	/*public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new VieFiles().setVisible(true);
			}
		});
	}*/

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JList jList1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}